name: E2E Tests (Ultra Simple)

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allow manual triggering

jobs:
  smoke-test:
    name: Smoke Test (Single Browser)
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build solution
      run: dotnet build -c Release --no-restore
    
    - name: Install Playwright Chromium
      run: |
        # Use dotnet tool approach which works better in CI
        dotnet tool install --global Microsoft.Playwright.CLI || echo "Already installed"
        playwright install chromium
        playwright install-deps chromium
    
    - name: Run Unit Tests First
      run: |
        dotnet test tests/ShopWeb.UnitTests/ \
          -c Release \
          --no-build \
          --logger "console;verbosity=minimal"
    
    - name: Run Single E2E Smoke Test
      run: |
        dotnet test ShopWeb.E2E.Tests/ \
          -c Release \
          --no-build \
          --filter "Category=Smoke" \
          --logger "console;verbosity=detailed" \
          --logger "trx;LogFileName=smoke-test-results.trx" \
          -- TestRunParameters.Parameter\(name=\"Browser\",value=\"chromium\"\) \
             TestRunParameters.Parameter\(name=\"SiteId\",value=\"A\"\)
      env:
        BROWSER: chromium
        SITE_ID: A
        TRACE_MODE: OnFailure
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: smoke-test-results
        path: |
          **/TestResults/**/*.trx
          **/artifacts/**/*
        retention-days: 7
    
    - name: Upload traces on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: smoke-test-traces
        path: |
          **/artifacts/**/*.zip
        retention-days: 3